### PR TITLE
Add support for translated street names

### PR DESCRIPTION
**Pull request by hannesj**

### CODE REVIEW

**Comment by buma** [comment]
Thanks for Pull request. I'll test it and merge it soon.

I don't know if you noticed but there exists similar class named [TranslatedString](https://github.com/opentripplanner/OpenTripPlanner/blob/master/src/main/java/org/opentripplanner/routing/alertpatch/TranslatedString.java) already in OTP which is currently used for Translated GTFS-RT alerts. Maybe if you can use it here new class isn't necesarry.

And I just noticed couple of days ago that now in OTP there is a function [generateI18N](https://github.com/opentripplanner/OpenTripPlanner/blob/master/src/main/java/org/opentripplanner/graph_builder/impl/osm/TemplateLibrary.java#L64) which gets all translated tag values from OSM. It was used when creating names and notes. Maybe you can use it.

**Comment by hannesj** [comment]
Hi @buma, and thanks for the review.

The TranslatedString reflects how GTFS-RT uses localized strings, and is not the best match for this. We could change the behaviour of that class, but I don't know if that is any better then having a new class that does exactly what we want.

The generateI18N looks interesting, I'll definitely take a look at that.

**Comment by hannesj** [comment]
Hi,

I removed the old TranslatedString, as it wouldn't fit as nicely with the new translation framework and adapted all code to use the new class. This needs more testing tough that it always works as expected. Also changed to parse the different translations from OSM using the TemplateLibrary.

**Comment by buma** [comment]
Great that you used generateI18n instead of custom code!

With removing `TranslatedString` there is problem. Serializer for `NonLocalizedString` for Jackson needs to be written and for other `I18NString` implementations that can happen in Alert where previously `TranslatedString` was used. Now There is error 500 and every time alert should be generated when requesting trip plan.

I'm not exactly sure where materializers are specified. If only `nonLocalizedString` can appear then serializer should just call `toString`, but problem should happen with `LocalizedStrings` I think.

**Comment by hannesj** [comment]
Hi,

I added a new class `LocalizedAlert`, which holds a reference to the alert and locale and does the localization on the fly when serializing the data. This should help with the issue. 

Also, I implemented localized notes for `StreetEdge`s, so that if no patterns are found, we attempt to translate the key. For the more complex notes and bikeshare names, we should probably create one more class implementing `I18NString`, which would be similar to LocalizedString, but hold a map of string arrays with the locale as key. That way we could both give the translated description and name for the station.

**Comment by buma** [comment]
That is a very nice solution for Alerts.

For bike shares I thought of another option. Why is it even necessary to send "bike station/share name" to client. Wouldn't be enough to send name and some option this vertex is bike share/bike station. And show bike share name on the client itself with client localization?

So that only name is saved. With alerts this doesn't work because it's dependent on tags but bikeshares only have names.

What do you think?

**Comment by hannesj** [comment]
Sounds good. That could be done in similar fashion to how elevators are done currently. Probably the same model should be applied to other mode changes (P+R etc) as well.

**Comment by buma** [comment]
Thanks that you changed matching.

How are elevators done currently?
I only found some Elevator edges in code and don't have any OSM files with working elevators.

**Comment by hannesj** [comment]
Currently there is some code in [GraphPathToTripPlanConverter.java](https://github.com/opentripplanner/OpenTripPlanner/blob/master/src/main/java/org/opentripplanner/api/resource/GraphPathToTripPlanConverter.java#L737) to do that. We could use a similar strategy, where a new value in the enum for relativeDirection is set and then use the translated name for the name.

**Comment by buma** [comment]
Thanks. I'll try to add bikeshares and P+R similar to elevators.

**Comment by buma** [comment]
I added client side translation support for bikeshares. Adding it to BikePark should be easy. But I can't test it because I don't have any P+R on local OSM files.

If you have any transit alerts please test with them, because client needed to be adjusted to new LocalizedAlert and I'm not completely sure it is all correct.

**Comment by hannesj** [comment]
Hi @buma,

Thanks, the changes in the front-end seem to work really nicely, you can check an example [here](http://matka-aika.com/reittiopas/?module=planner&fromPlace=60.16542574699484%2C24.9444580078125&toPlace=60.16756070532547%2C24.858112335205078&time=11%3A12pm&date=2015-02-26&mode=TRANSIT%2CWALK&maxWalkDistance=1609.344&arriveBy=false&wheelchair=false&showIntermediateStops=false&locale=en&itinIndex=0)

Unfortunately I don't have any bikeshares in my graph, so I can't test those.

**Comment by buma** [comment]
It looks very nice but I found one problem. When looking at your example path with my locale "sl" I get probably Finnish alert about line 20N diversion. But if I use English locale I get same information in English.

It would be nicer IMHO if information would be shown in English if it isn't found in requested locale.

And another thing. I don't know where do you get diversion alerts (GTFS-rt or somewhere else) but usually alert header is only short information and full description is in alert description. This also makes nicer display of alert. Because full description is visible only when you open the alert.

**Comment by hannesj** [comment]
Displaying the information in English would maybe be preferred, but the question is,what if we would only have the information in Finnish and Swedish, which one should be shown then? There is no way to specify a "default locale" in a GTFS-RT feed.

I changed now so that the text is put into the description, as we only get a single line of text from our internal disruption information system. [Current feed](http://www.poikkeusinfo.fi/xml/v3)

**Comment by hannesj** [comment]
Hmm, the GTFS-RT specification states the following:

> The resolution proceeds as follows: If the UI language matches the language code of a translation, the first matching translation is picked. If a default UI language (e.g., English) matches the language code of a translation, the first matching translation is picked. If some translation has an unspecified language code, that translation is picked.

So probably the default language (which should be set only in one place in OTP) should be taken into consideration if the correct translation does not exist.

**Pull request merged**
